First Pull Request
MCLRDRI15/React-JS-project-PokeApi-AlejandroRios pull request #2
Opened 2021-08-09 17:28 UTC by MCLRDRI15

2021-08-10 14:09 UTC, hackeo1 requested changes
- make the images naming convention consistent
- check the consistency of the color units

2021-08-10 14:09 UTC, hackeo1 commented on package.json
> +    "yarn": "^1.22.11"
yarn should not be a dependency

2021-08-10 14:09 UTC, hackeo1 commented on public/index.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
use a dependency instead of cdn

2021-08-10 14:09 UTC, hackeo1 commented on public/index.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="
use a dependency instead of cdn

2021-08-10 14:09 UTC, hackeo1 commented on src/Redux/Actions/pokemonActions.js
> +export const FETCH_SUCCESS2 = "FETCH_POSTS_SUCCESS2";
name the actions accordingly, these names are too generic

2021-08-10 14:09 UTC, hackeo1 commented on src/Redux/Actions/pokemonActions.js
> +    ),
making modifications over the state is the responsibility of the reducers, not the actions

2021-08-10 14:09 UTC, hackeo1 commented on src/components/bubbles/bubbles.js
> +      <div className="bubble"></div>
use a function to produce repetitive tags

2021-08-10 14:09 UTC, hackeo1 commented on src/components/littleChart/CompareArea.module.css
> +  --border-name: rgb(97, 97, 97);
use consistent units for the color values

2021-08-10 14:09 UTC, hackeo1 commented on src/components/pokemon-selected/showPokemonCompare.js
> +          </div>
this is repeated bellow, with a different pokemon, an a different class, use a function to avoid repeating it

2021-08-11 17:06 UTC, jugonz31 reviewed
please take a look at how you name items, classes, components, and folders in all the project:

use UpperCamelCase for components (**MyComponent**.js - export default **MyComponent**)
use camelCase for constants, props, variables, etc. (`let **myVariable** = 0; const **myConst** = true;`)
use snake_case or kebab-case for CSS classes: (`.**my-class** {}`)
use kebab-case for folders (src/components/**my-component**/MyComponent.js)

2021-08-11 17:06 UTC, jugonz31 commented on src/components/Home-page/Home.module.css
> +.welcome-tittle {
fix typo 'tittle'

2021-08-11 17:06 UTC, jugonz31 commented on src/components/Home-page/Home.module.css
> +}
make sure you are consistent with the spacing between different css classes

2021-08-11 17:06 UTC, jugonz31 commented on src/components/chartsFolder/Charts.module.css
> +.rectangle {
pay attention to how you name this file, compared with other CSS Modules, sometimes you use UpperCamelCase, sometimes you use CamelCase, sometimes you just use lowercase, this needs to be consistent and you need to set and follow an standard

2021-08-11 17:06 UTC, jugonz31 commented on src/components/input-form/form.js
> +import CompareArea from "../littleChart/CompareArea";
usually, we order import statements in some way, where you first put React imports, followed by libraries, then components, and finally CSS classes, it would be good if you try ordering these statements all around the project. Not a priority but would be good to keep that in mind

2021-08-11 17:06 UTC, jugonz31 commented on src/components/input-form/form.js
> +  let [booleanValue, hamburguerStylesHandler] = useState(false);
avoid using generic names like 'booleanValue' and try using more descriptive names

2021-08-11 17:06 UTC, jugonz31 commented on src/components/input-form/form.js
> +  let [booleanValue, hamburguerStylesHandler] = useState(false);
for the useState items, we use to have something like 
`[<valueName>, set<valueName>] = useState(false);`

2021-08-11 17:06 UTC, jugonz31 commented on src/components/input-form/formStyles.module.css
> +.linkColor {
same as mentioned above, the CSS classes should also have a standard. You must use camelCase or kebab-case or UpperCamelCase in every CSS class, but only one of those. here you have .linkColor (camelCase) but then later you have .text-tittle (kebab-case)

https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

2021-08-11 17:06 UTC, jugonz31 commented on src/components/input-form/formStyles.module.css
> +.linkColor {
for CSS classes is more common avoiding uppercase letters, so, try using snake_case or kebab-case

2021-08-11 17:06 UTC, jugonz31 commented on src/components/littleChart/CompareArea.js
> +    <div className={showchart ? "littleChart-container" : "hidden"}>
showChart is more readable

2021-08-11 17:06 UTC, jugonz31 commented on src/components/pokemon-selected/showPokemonCompare.js
> +    <ScrollLock isActive={ViewState}>
do not start variables or constants with uppercase. In React only the Components must start with uppercase and be UpperCamelCase. variables and constants should be camelCase

2021-08-12 16:27 UTC, jugonz31 reviewed
Your folder and file names still having issues with the lower and upper case. Maybe in your local machine it is OK now, but Git does not recognize those changes by itself, so please take a look at how to fix that

2021-08-13 14:29 UTC, jugonz31 approved these changes
Besides those two comments, I see you fixed most of the things that were wrong. Good job

2021-08-13 14:29 UTC, jugonz31 commented on src/components/pokemons-selected/viewMode.js
> +import React from "react";
Remember, components should start with uppercase

2021-08-13 14:29 UTC, jugonz31 commented on src/components/pokemons-list/Pokelist.module.css
> +.pokelist-section {
The component is called PokeList, but the module has lowercase in the L

2021-08-13 16:10 UTC, hackeo1 approved these changes

2021-08-13 16:11 UTC, merged